### PR TITLE
Implemented latest tag handling, policy added for latest tags

### PR DESCRIPTION
**Pull request by jtcressy**
Hi! I believe I have found a solution to not only my own issue, #21, but also a partial solution for issue #11. 

#11 would still like polling, however, which has not been addressed in this PR.

Please look this over just in case I messed something up or have extraneous code.

### CODE REVIEW

**Comment by rusenask** [comment]
Hey, thanks for PR! :) 

There are several issues with this approach:
1. If you are versioning your images through semver and then still push `latest` tag into your registry (ie: you tag all your images with both semver and latest) then Keel would by default bump version to `latest` and ignore other updates even if those are tagged as semver, therefore you would need to recreate deployment.
2. Kubernetes ignores deployment updates if the tag hasn't changed. Trying to figure it out now.. 

Currently working on `polling` branch, 
added a few utility packages, one for getting image digest: https://github.com/rusenask/keel/tree/feature/polling/registry
another to work with images (tags, full remote names):
https://github.com/rusenask/keel/tree/feature/polling/util/image 
and also splitting kubernetes container update into a separate functions as it looks the clean approach (semver and force paths): https://github.com/rusenask/keel/blob/feature/polling/provider/kubernetes/deployment.go

The next step would probably be to decide how we want to handle updates when the tag remains the same. K8s devs apparently are reluctant to add this functionality and to be honest it's quite bad to tag images with the same tag. I would like to hear your opinion on https://github.com/rusenask/keel/issues/11 as well, in pubsub/webhook case destroying/recreating deployments looks like the only option if we don't want to supply registry auth details to every deployment (to check digest).

@jtcressy, could you add some tests in the version package and kubernetes provider to demonstrate behaviour ? `latest` tags should be ignored if policy is not `force` or `onlatest` ? 
 
It would be great if you could port your changes for the `polling` branch as I haven't started working on `latest` tag handling and I could also deal with the deployment updates even if the tag remains the same.

**Comment by jtcressy** [comment]
I'll start working with the polling branch and see where i can go with that. 

I think we can get kubernetes to force an update from latest -> latest by doing latest -> 0.0.0 -> latest and update the deployment each time. So we pretty much need to go through the ``impactedDeployments()`` routine twice.

A demonstration would be to run these commands in kubectl:
```
kubectl set image pods <pod> <container>=<repo>/<image>:0.0.0
kubectl set image pods <pod> <container>=<repo>/<image>:latest
```
As long as ``imagePullPolicy`` is set to ``Always``, it will re-pull the image for latest.

**Comment by rusenask** [comment]
I have currently split that deployment check function into two files: unversioned_updates and versioned_updates. So unversioned function has become quite simple - if the image name matches - new tag is set. I think I will use annotations to pass extra info to the updateDeployments function, it could have something like `keel.sh/updateStrategy` key which could carry info about.. update strategy :) i.e.  `keel.sh/updateStrategy=recreated`,  `keel.sh/updateStrategy=rollingUpdate` (default).

I would like to ask you to wait a little bit till I merge that code into develop branch as it's still work in progress. I hope that by using `force` policy it could solve your use case :)

**Comment by jtcressy** [comment]
Alright, i'll stay tuned for that merge. In the meantime i'm pushing image updates manually with the kubectl command mentioned above.

**Comment by rusenask** [comment]
I will go with your solution, looks less hacky than any other alternative :)

**Comment by rusenask** [comment]
Got it working, now just with regular tags (haven't tested simple `latest` tag yet) but got unit tests for those. Also, haven't done any regression testing for pubsub/webhook triggers as it's getting pretty late. Apparently k8s doesn't allow you to do double update of the same deployment and asks for refresh. I guess it's good but made life harder :) If you could build an image from latest polling branch and check whether it works for you with `force` policy - would be great :)

screen shot 2017-07-04 at 00 14 17

**Comment by rusenask** [comment]
Closing this down as the same functionality can be achieved with `force` policy now :)

**Pull request closed without merging**
